language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
env:
    -TOXENV=py26
    -TOXENV=py27
    -TOXENV=py34

# command to install dependencies
install: "pip install -U tox"
# command to run tests
script: tox -e $TOXENV
